### PR TITLE
Add serverless leetcode function

### PR DESCRIPTION
**Pull request by Gabau**

### CODE REVIEW

**Review by Nafeij — APPROVED** [review]
LG, but I'm wondering if there is a way to somehow populate the Environment and TestCases entries as well?

**Comment by Gabau** [comment]
Idt leetcode provides details on their test cases on graphql

**Review by kflim — APPROVED** [review]
LGTM

**Comment by Gabau** [comment]
https://github.com/CS3219-AY2324S1/ay2324s1-assignment-6-g39 pushed to this place instead, don't think there is a need to merge into master?

**Pull request closed without merging**
